spring:
  application:
    name: udemy-hexagonal-architecture
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal

address:
  client:
    url: http://localhost:8082/addresses